function [rou44] = JvZhen5(Op0,Oc,Od,Oa,dp,dc,dr,gme,g23,gmm,g24,gmr,g43,G21,G23,G43,theta_m,theta_p,theta_c)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

Op1 = Op0*exp(1i*theta_p); Op2 = Op0*exp(-1i*theta_p);
Oc1 = Oc*exp(1i*theta_c); Oc2 = Oc*exp(-1i*theta_c);
Od1 = Od; Od2 = Od;
A=zeros(16,16);
B=zeros(16,1);
x=zeros(16,1);

A =[               0,           0,                0,             -gme, -Oa*sin(theta_m),       0,                  0,                0,                0,             -dp,  Oa*cos(theta_m),       0,               -Oc1,                0,               0;...
               0,           0,                0,  Oa*sin(theta_m),             -g23,       0,                  0,                0,                0, Oa*cos(theta_m),              -dc,     Od2,                Op1,                0,               0;...
 Oa*sin(theta_m),           0, -Oa*sin(theta_m),                0,                0,       0,               -gmm,                0,                0,            -Oc2,             -Op1,       0,            dc - dp,                0,            -Od1;...
               0,           0,                0,                0,                0,    -g24,                  0,                0,                0,               0,              Od1, dr - dc,                  0,             -Oc1,             Op1;...
               0,           0,                0,                0,                0,       0,                  0, -Oa*sin(theta_m),             -gmr,               0,                0,    -Op1,               -Od2, -Oa*cos(theta_m),    dc - dp - dr;...
               0,           0,                0,                0,                0,       0,                  0,             -g43,  Oa*sin(theta_m),               0,                0,    -Oc1,                  0,               dr, Oa*cos(theta_m);...
               0,         G21,                0,                0,                0,       0, -2*Oa*sin(theta_m),                0,                0,     - Op1 - Op2,                0,       0, -2*Oa*cos(theta_m),                0,               0;...
               0, - G21 - G23,                0,                0,                0,       0,                  0,                0,                0,       Op1 + Op2,        Oc1 + Oc2,       0,                  0,                0,               0;...
            -G43,   G23 - G43,             -G43,                0,                0,       0,  2*Oa*sin(theta_m),                0,                0,               0,      - Oc1 - Oc2,       0,  2*Oa*cos(theta_m),        Od1 + Od2,               0;...
             Op1,        -Op1,                0,               dp, -Oa*cos(theta_m),       0,                Oc1,                0,                0,            -gme, -Oa*sin(theta_m),       0,                  0,                0,               0;...
               0,        -Oc1,              Oc1, -Oa*cos(theta_m),               dc,    -Od2,                Op1,                0,                0, Oa*sin(theta_m),             -g23,       0,                  0,                0,               0;...
 Oa*cos(theta_m),           0, -Oa*cos(theta_m),              Oc2,             -Op1,       0,            dp - dc,                0,              Od1,               0,                0,       0,               -gmm,                0,               0;...
               0,           0,                0,                0,             -Od1, dc - dr,                  0,              Oc1,              Op1,               0,                0,    -g24,                  0,                0,               0;...
               0,           0,                0,                0,                0,    -Op1,                Od2, -Oa*cos(theta_m),     dp - dc + dr,               0,                0,       0,                  0,  Oa*sin(theta_m),            -gmr;...
             Od2,         Od2,            2*Od2,                0,                0,    -Oc1,                  0,               dr, -Oa*cos(theta_m),               0,                0,       0,                  0,              g43, Oa*sin(theta_m)];
 
    B=[0; 0; 0; 0; 0; 0; 0; 0;-G43; 0; 0; 0; 0; 0; Od2];
    x=A\B;

rou44=1-x(1)-x(2)-x(3);

end
